yml experimentation

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,49 +11,49 @@
 #node_js: '10.14.0'
 
 
-# FROM DOCS
+# FROM DOCS - 
 
-matrix:
-  include:
-    - os: osx
-      osx_image: xcode9.4
-      language: node_js
-      node_js: "10"
-      env:
-        - ELECTRON_CACHE=$HOME/.cache/electron
-        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
+# matrix:
+#   include:
+#     - os: osx
+#       osx_image: xcode9.4
+#       language: node_js
+#       node_js: "10"
+#       env:
+#         - ELECTRON_CACHE=$HOME/.cache/electron
+#         - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
 
-    - os: linux
-      services: docker
-      language: generic
+#     - os: linux
+#       services: docker
+#       language: generic
 
-cache:
-  directories:
-    - node_modules
-    - $HOME/.cache/electron
-    - $HOME/.cache/electron-builder
-    - $HOME/Library/Caches/Homebrew
+# cache:
+#   directories:
+#     - node_modules
+#     - $HOME/.cache/electron
+#     - $HOME/.cache/electron-builder
+#     - $HOME/Library/Caches/Homebrew
 
-script:
-  - |
-    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
-      docker run --rm \
-        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
-        -v ${PWD}:/project \
-        -v ~/.cache/electron:/root/.cache/electron \
-        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
-        electronuserland/builder:wine \
-        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
-    else
-      yarn release
-    fi
-before_cache:
-  - brew cleanup
-  - rm -rf $HOME/.cache/electron-builder/wine
+# script:
+#   - |
+#     if [ "$TRAVIS_OS_NAME" == "linux" ]; then
+#       docker run --rm \
+#         --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
+#         -v ${PWD}:/project \
+#         -v ~/.cache/electron:/root/.cache/electron \
+#         -v ~/.cache/electron-builder:/root/.cache/electron-builder \
+#         electronuserland/builder:wine \
+#         /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
+#     else
+#       yarn release
+#     fi
+# before_cache:
+#   - brew cleanup
+#   - rm -rf $HOME/.cache/electron-builder/wine
 
-branches:
-  except:
-    - "/^v\\d+\\.\\d+\\.\\d+$/"
+# branches:
+#   except:
+#     - "/^v\\d+\\.\\d+\\.\\d+$/"
 
 # ...
 
@@ -83,11 +83,11 @@ branches:
 #  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi
 
   # These commands are executed before the scripts are executed
-install:
+#install:
   # On OS X we first need to install Yarn via Homebrew
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
+  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
   # Install all dependencies listed in your package.json file
-  - yarn
+  # - yarn
 
 # script:
 #  - echo "Deploy linux version to GitHub"
@@ -98,3 +98,50 @@ install:
 
 #  - echo "Deploy mac version to GitHub"
 #  - if [[ "$TRAVIS_BRANCH" == "travis-config" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn gh-publish:mac; fi
+
+
+
+## FROM ISSUE: https://github.com/electron-userland/electron-builder/issues/1751
+
+osx_image: xcode8.3
+
+dist: trusty
+sudo: false
+
+language: node_js
+node_js: "10"
+
+env:
+  global:
+    - ELECTRON_CACHE=$HOME/.cache/electron
+    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
+
+os:
+  - linux
+  - osx
+
+cache:
+  directories:
+  - node_modules
+  - $HOME/.cache/electron
+  - $HOME/.cache/electron-builder
+  - $HOME/.npm/_prebuilds
+
+before_install:
+  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
+  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
+  - export PATH="$HOME/.yarn/bin:$PATH"
+
+install:
+  - yarn
+
+script:
+  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release; fi
+  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release -- --mac --win; fi
+
+before_cache:
+  - rm -rf $HOME/.cache/electron-builder/wine
+
+branches:
+  except:
+    - "/^v\\d+\\.\\d+\\.\\d+$/"
